// <auto-generated />
namespace VirtoCommerce.B2BCustomerModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PreInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221354359_PreInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
